# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da8fbee0ae5859065636b0c359f32dabda7474777f303c161495d3ce2b60fca3f78b12d651faffb6c242b296518d52d6c46553475524bd37c411bb3004c176a9

test:
  secret_key_base: ccfd42de20df60ea55747b532c2da4e70c2627184dddf656b1706b63b3d72b64c38a00f4fb0147055bb7c0534301ebe3a3f4e5dd096954b06db9bb399603ca89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
